package tutor

import (
	"encoding/json"
	"log"
	"net/http"

	"github.com/jarrancarr/ChexxServer/utils"
)

type Step struct {
	Title      string     `json:"title"`
	Width      int8       `json:"width"`
	PosX       int8       `json:"posX"`
	PosY       int8       `json:"posY"`
	Background string     `json:"background"`
	Text       []string   `json:"text"`
	White      []string   `json:"white"`
	Black      []string   `json:"black"`
	Hilite     [][]string `json:"hilite"`
	Log        []string   `json:"log"`
	Answer     [][]string `json:"answer"`
	Order      []string   `json:"order"`
	Hint       []string   `json:"hint"`
}

type Lesson struct {
	Step []Step `json:"step"`
}

var Lessons map[string]Lesson = map[string]Lesson{
	"Intro": {
		Step: []Step{
			{Title: "Welcome to Chexx", Width: 70, PosX: 50, PosY: 50, Background: "#002020a0", Log: []string{},
				Black: []string{"Qf31", "Kf33", "Ea31", "Ia33", "Pf4", "Nf53", "Ba4", "Aa53", "Sb4"},
				White: []string{"Qd33", "Kd31", "Ec33", "Ic31", "Pe4", "Nd53", "Bd4", "Ac53", "Sc4"},
				Text: []string{
					"h1:::Chexx is Chess varient.", "h3:::Chexx is played on a hexagonal board, and here are the types of pieces at your command.",
					"You might find some familiar, and others not so."}},
			{Title: "Chess Pieces", Width: 70, PosX: 50, PosY: 50, Background: "#f0f02050",
				Black: []string{"Qf31", "Kf33", "Pf4", "Nf53", "Ba4", "Sb4"},
				White: []string{""},
				Text: []string{"h2:::There are 9 types of pieces.  Five correspond rather directly from Chess.",
					"Pawn: marches forward, attacks to the forward flanks.",
					"Knight: two spaces along a column and one to the right or left.",
					"Bishop: straignt alongs diagonals until blocked.",
					"Rook: straight along columns",
					"Queen: combines the power of the Rook and Bishop.",
					"King: one space in any direction.",
				}},
			{Title: "New Pieces", Width: 70, PosX: 50, PosY: 50, Background: "#f0f02050",
				Black: []string{"Ea31", "Ia33", "Aa53", "Sb4"},
				White: []string{},
				Text: []string{"h2:::The 4 remaining pieces you might find quite derivative.",
					"Spearman: like Pawns, but attacks to the forward diagonals instead of forward flanks.",
					"Archer: similar to Knights, but instead of two spaces along a column, they take three spaces, then and one to the right or left.",
					"Prince: A Rook and a Knight.",
					"Princess: The Bishop and Archer.",
				}},
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#00f0f050",
				Black: []string{"Qf31", "Kf33", "Ea31", "Ia33", "Pf4", "Nf53", "Ba4", "Aa53", "Sb4"},
				White: []string{"Qd33", "Kd31", "Ec33", "Ic31", "Pe4", "Nd53", "Bd4", "Ac53", "Sc4"},
				Text:  []string{"If you do have any Chess experience, you will find very little conceptually that is terribly different.  Only after a few games you should be comfortable with the hexagonal layout.  Things that are actually different is still quite derivitive from existing Chess concepts, so you should have no trouble learning them."}},
			{Title: "White Army", Width: 40, PosX: 50, PosY: 40,
				White: []string{"Rd54", "Rd5", "Rc52", "Nd53", "Nd51", "Nc33", "Bc53", "Bc55", "Bd52", "Qd41", "Kc44", "Id31", "Ed4", "Pd55", "Pd44", "Pd33", "Pd21", "Pc22", "Pc31", "Pc41", "Pc51", "Sd43", "Sd32", "Sd2", "Sc32", "Sc42", "Ad42", "Ad3", "Ac43"},
				Black: []string{},
				Text:  []string{"You have 8 Pawns and 5 Spearmen. Three each of Rooks, Bishops, Knights and Archers.  Then of course, one Prince, Princess, Queen and King"}},
			{Width: 40, PosX: 50, PosY: 40,
				White:  []string{"Rd54", "Rd5", "Rc52", "Nd53", "Nd51", "Nc33", "Bc53", "Bc55", "Bd52", "Qd41", "Kc44", "Id31", "Ed4", "Pd55", "Pd44", "Pd33", "Pd21", "Pc22", "Pc31", "Pc41", "Pc51", "Sd43", "Sd32", "Sd2", "Sc32", "Sc42", "Ad42", "Ad3", "Ac43"},
				Black:  []string{},
				Text:   []string{"The 8 pawns..."},
				Hilite: [][]string{{"d55 d44 d33 d21 c22 c31 c41 Pc51", "stroke", "#ff4"}}},
			{Width: 40, PosX: 50, PosY: 40,
				White:  []string{"Rd54", "Rd5", "Rc52", "Nd53", "Nd51", "Nc33", "Bc53", "Bc55", "Bd52", "Qd41", "Kc44", "Id31", "Ed4", "Pd55", "Pd44", "Pd33", "Pd21", "Pc22", "Pc31", "Pc41", "Pc51", "Sd43", "Sd32", "Sd2", "Sc32", "Sc42", "Ad42", "Ad3", "Ac43"},
				Black:  []string{},
				Text:   []string{"... 5 spearmen,"},
				Hilite: [][]string{{"d43 d32 d2 c32 c42", "stroke", "#ff4"}}},
			{Width: 40, PosX: 50, PosY: 40,
				White:  []string{"Rd54", "Rd5", "Rc52", "Nd53", "Nd51", "Nc33", "Bc53", "Bc55", "Bd52", "Qd41", "Kc44", "Id31", "Ed4", "Pd55", "Pd44", "Pd33", "Pd21", "Pc22", "Pc31", "Pc41", "Pc51", "Sd43", "Sd32", "Sd2", "Sc32", "Sc42", "Ad42", "Ad3", "Ac43"},
				Black:  []string{},
				Text:   []string{"3 Knights (red), 3 Bishops (blue), 3 Rooks (yellow), and 3 Archers (green)..."},
				Hilite: [][]string{{"d53 d51 c33", "stroke", "#f00"}, {"c53 c55 d52", "stroke", "#00f"}, {"d54 d5 c52", "stroke", "#ff0"}, {"d42 d3 c43", "stroke", "#0f0"}}},
			{Width: 40, PosX: 50, PosY: 40,
				White:  []string{"Rd54", "Rd5", "Rc52", "Nd53", "Nd51", "Nc33", "Bc53", "Bc55", "Bd52", "Qd41", "Kc44", "Id31", "Ed4", "Pd55", "Pd44", "Pd33", "Pd21", "Pc22", "Pc31", "Pc41", "Pc51", "Sd43", "Sd32", "Sd2", "Sc32", "Sc42", "Ad42", "Ad3", "Ac43"},
				Black:  []string{},
				Text:   []string{"...and the Royal family:", "The Prince on his horse, the Princess with her bow,", "and of course, his magisty, the King and her royal highness, the Queen."},
				Hilite: [][]string{{"d41 c44 d31 d4", "stroke", "#a0f"}}},
			{Width: 40, PosX: 50, PosY: 60,
				White: []string{},
				Black: []string{"Ra5", "Rf52", "Ra54", "Nf53", "Nf55", "Na31", "Ba53", "Ba51", "Bf54", "Qf44", "Ka41", "If33", "Ea4", "Pf51", "Pf41", "Pf31", "Pf22", "Pa21", "Pa33", "Pa44", "Pa55", "Sf42", "Sf32", "Sa2", "Sa32", "Sa43", "Af43", "Aa3", "Aa42"},
				Text:  []string{"Black has the identical army."}},
		},
	},

	"Quick": {
		Step: []Step{
			{Title: "Quick Start", Width: 70, PosX: 50, PosY: 58, Background: "#b02020a0", Log: []string{}, Order: []string{"menu tutor"},
				Black: []string{"Ra5", "Rf52", "Ra54", "Nf53", "Nf55", "Na31", "Ba53", "Ba51", "Bf54", "Qf44", "Ka41", "If33", "Ea4", "Pf51", "Pf41", "Pf31", "Pf22", "Pa21", "Pa33", "Pa44", "Pa55", "Sf42", "Sf32", "Sa2", "Sa32", "Sa43", "Af43", "Aa3", "Aa42"},
				White: []string{"Rd54", "Rd5", "Rc52", "Nd53", "Nd51", "Nc33", "Bc53", "Bc55", "Bd52", "Qd41", "Kc44", "Id31", "Ed4", "Pd55", "Pd44", "Pd33", "Pd21", "Pc22", "Pc31", "Pc41", "Pc51", "Sd43", "Sd32", "Sd2", "Sc32", "Sc42", "Ad42", "Ad3", "Ac43"},
				Text:  []string{"h2:::The match begins in this opening position.", "White moves first."}},
			{Title: "Pawns and Spearmen", Width: 70, PosX: 50, PosY: 40, Background: "#b02020a0", Log: []string{},
				Black:  []string{"Ra5", "Rf52", "Ra54", "Nf53", "Nf55", "Na31", "Ba53", "Ba51", "Bf54", "Qf44", "Ka41", "If33", "Ea4", "Pf51", "Pf41", "Pf31", "Pf22", "Pa21", "Pa33", "Pa44", "Pa55", "Sf42", "Sf32", "Sa2", "Sa32", "Sa43", "Af43", "Aa3", "Aa42"},
				White:  []string{"Rd54", "Rd5", "Rc52", "Nd53", "Nd51", "Nc33", "Bc53", "Bc55", "Bd52", "Qd41", "Kc44", "Id31", "Ed4", "Pd55", "Pd44", "Pd33", "Pd21", "Pc22", "Pc31", "Pc41", "Pc51", "Sd43", "Sd32", "Sd2", "Sc32", "Sc42", "Ad42", "Ad3", "Ac43"},
				Text:   []string{"h2:::Pawns move only forward one or two spaces.  Only from a Pawn or Spearmen opening position may a pawn move two spaces.", "h4:::Select any pawn by clicking, then click on an advancing space."},
				Hilite: [][]string{{"d55 d44 d33 d21 c22 c31 c41 c51 d43 d32 d2 c32 c42", "stroke", "#ff4"}},
				Answer: [][]string{{"", "Nope.", "30,80,6,#f00,#20202070"},
					{"d55 d44 d33 d21 c22 c31 c41 c51", "", "-"},
					{"d43 d32 d2 c32 c42 d54 d5 c52 d53 d51 c33 c53 c55 d52 d41 c44 d31 d4", "Lets choose a pawn instead.", "20,80,6,#f00,#20202070"},
					{"d55~e4 d55~e41 d44~e3 d44~e31 d33~e2 d33~e21 d21~d11 d21~e c22~c11 c22~c c31~c2 c31~b22 c41~c3 c41~b33 c51~c4 c51~b44", "That is a valid Pawn move.", "20,80,2,#f00,#20202070"},
					{"a5 a52 a54 f53 f55 a31 a53 a51 f54 f44 a41 f33 a4 f51 f41 f31 f22 a21 a33 a44 a55 f42 f32 a2 a32 a43 f43 a3 a42", "For the moment, that is not your army.", "10,82,5,#6F6,#80808040"},
				},
			},
			{Title: "Pawns and Spearmen", Width: 70, PosX: 50, PosY: 40, Background: "#b02020a0", Log: []string{},
				Black:  []string{"Ra5", "Rf52", "Ra54", "Nf53", "Nf55", "Na31", "Ba53", "Ba51", "Bf54", "Qf44", "Ka41", "If33", "Ea4", "Pf51", "Pf41", "Pf31", "Pf22", "Pa21", "Pa33", "Pa44", "Pa55", "Sf42", "Sf32", "Sa2", "Sa32", "Sa43", "Af43", "Aa3", "Aa42"},
				White:  []string{"Rd54", "Rd5", "Rc52", "Nd53", "Nd51", "Nc33", "Bc53", "Bc55", "Bd52", "Qd41", "Kc44", "Id31", "Ed4", "Pd55", "Pd44", "Pd33", "Pd21", "Pc22", "Pc31", "Pc41", "Pc51", "Sd43", "Sd32", "Sd2", "Sc32", "Sc42", "Ad42", "Ad3", "Ac43"},
				Text:   []string{"h2:::Pawns move only forward one or two spaces.  Only from a Pawn or Spearmen opening position may a pawn move two spaces.", "The two space option is still available even after a move once, if they happen to move to another's 'opening position'."},
				Hilite: [][]string{{"d55 d44 d33 d21 c22 c31 c41 Pc51 d43 d32 d2 c32 c42", "stroke", "#ff4"}}},
			{Title: "Chess Pieces", Width: 70, PosX: 50, PosY: 50, Background: "#f0f02050",
				Black: []string{"Qf31", "Kf33", "Pf4", "Nf53", "Ba4", "Sb4"},
				White: []string{""},
				Text: []string{"h2:::There are 9 types of pieces.  Five correspond rather directly from Chess.",
					"Pawn: marches forward, attacks to the forward flanks.",
					"Knight: two spaces along a column and one to the right or left.",
					"Bishop: straignt alongs diagonals until blocked.",
					"Rook: straight along columns",
					"Queen: combines the power of the Rook and Bishop.",
					"King: one space in any direction.",
				}},
		},
	},
	"Interface": {
		Step: []Step{
			{Title: "Interface", Width: 40, PosX: 70, PosY: 30, Background: "#f0f02050", Order: []string{"menu tutor", "draw circle 91,8,8,#F00"}, Log: []string{},
				Black: []string{}, White: []string{},
				Text: []string{"All help and tutorials are accessed through the <?> menu in the upper right.", "When selected, all the individual tutorials are shown in the black circular area."}},
			{Title: "Main Menu", Width: 40, PosX: 70, PosY: 60, Background: "#f0f02050",
				Black: []string{}, White: []string{}, Order: []string{"menu main", "draw circle 91,91,8,#F00"},
				Text: []string{"On the lower right, it the main menu.", "Here is where you will find access to logging in, matches and quite a bit more."}},
			{Title: "Clocks", Width: 40, PosX: 30, PosY: 50, Background: "#f0f02050",
				Black: []string{}, White: []string{}, Order: []string{"menu ", "draw circle 9,9,8,#F00", "draw circle 9,91,8,#F00"},
				Text: []string{"To the left of the board are the clocks.",
					"During a match, you will see how much time you have left.  Also, you move isn't confirmed until you tap your clock.  Until then, your move will not be final and your clock will run down.",
					"There are two hands on the clock.  The larger black one is your move clock.  It will circle once around and stop.  Then, the red hand begins to count down.  This is your game clock.  Once it reaches the top, its game over... you lost."}},
			{Title: "Ledger", Width: 55, PosX: 50, PosY: 50, Background: "#00606090",
				Black: []string{}, White: []string{},
				Log: []string{"Pc31~b22", "Nf53~f21", "Id31~d", "Sa32~a22", "IdxSa2", "Qf44xIa2", "Ed4~c11", "Aa3~f"},
				Text: []string{"The thick black ring around the board has a few purposes.",
					"You will have notices that menu options are shown here.",
					"During a match, though, it records each move with tabs that circle the board.  Hovinging over one highlights that move on the board.  Clicking on a tab will give detailed information about the move."}},
		},
	},
	"Rules": {
		Step: []Step{
			{Title: "Rules", Width: 70, PosX: 50, PosY: 50, Background: "#20202050", Log: []string{},
				Black: []string{}, White: []string{},
				Text: []string{"A Chexx match begins with White making the first move and then each side makes a legal moves in turn until the game and ends in checkmate, stalemate, draw, timeout, surrender.",
					"The ultimate goal of each player is to achieve checkmate.  Checkmate is when you are attacking the opponent's King and there is no move that can free him of an attack.",
					"Lest you can achieve checkmate, stalemate might be your next option.  If you can manage to position your King in such a way as to be safe, but any move you make will check your King, meaning he is attacked."}},
		},
	},
	"Board": {
		Step: []Step{
			{Title: "Battlefield", Width: 70, PosX: 50, PosY: 50, Background: "#00000010", Order: []string{"menu tutor"},
				Black: []string{}, White: []string{}, Log: []string{},
				Text: []string{"The Chexx battlefield is set on a hexagonal grid.  Black spaces, white spaces and neutral spaces."}},
			{Title: "Compass Rose", Width: 70, PosX: 50, PosY: 65, Background: "#00000010", Black: []string{}, White: []string{}, Hilite: [][]string{{"*", "stroke", "#ff0"}},
				Text: []string{"The dead center of the is marked with a gold medallion... the 'compass rose'.", "Notated by '*'."}},

			{Title: "Columns", Width: 25, PosX: 10, PosY: 50, Background: "#999999a0", Black: []string{}, White: []string{},
				Hilite: [][]string{{"a5 a4 a3 a2 a1 a * d d1 d2 d3 d4 d5", "stroke", "#ff0"}, {"a52 a42 a32 a22 b1 b11 c1 c21 c32 c43 c54", "stroke", "#0f0"}, {"f54 f43 f32 f21 f1 e11 e1 d22 d32 d42 d52", "stroke", "#00f"}},
				Text: []string{
					"If you remember from chess, rows run horizontal and columns run vertical.  On the Hexagonal grid, it is bit different... there are still vertical columns.",
					"Highlighted in yellow, is the center vertical column.",
					"In green is the a52~c54 column, and in blue, the f54~d52 column"}},
			{Title: "", Width: 20, PosX: 15, PosY: 15, Background: "#888888a0", Black: []string{}, White: []string{},
				Hilite: [][]string{{"a5 a4 a3 a2 a1 a d d1 d2 d3 d4 d5", "stroke", "#ff0"}, {"b5 b4 b3 b2 b1 b e e1 e2 e3 e4 e5", "stroke", "#08f"}, {"c5 c4 c3 c2 c1 c f f1 f2 f3 f4 f5", "stroke", "#0F4"}},
				Text:   []string{"But columns are a bit more arbitrary on this trilinear topology...", "Lets keep the central vertical column in yellow, but will add the other columns that run through the center."}},

			{Title: "", Width: 20, PosX: 15, PosY: 15, Background: "#888888a0", Black: []string{}, White: []string{},
				Hilite: [][]string{{"a5 a4 a3 a2 a1 a d d1 d2 d3 d4 d5", "stroke", "#ff0"}, {"b5 b4 b3 b2 b1 b e e1 e2 e3 e4 e5", "stroke", "#08f"}, {"c5 c4 c3 c2 c1 c f f1 f2 f3 f4 f5", "stroke", "#0F4"}},
				Text:   []string{"Given this 3 axis format, rows and column coordinate system is less than ideal.", "So we introduce a new coordinate system."}},

			{Title: "", Width: 60, PosX: 50, PosY: 90, Background: "#888888a0", Black: []string{}, White: []string{},
				Hilite: [][]string{
					{"a55 a54 a53 a53 a51 a5 a44 a43 a42 a41 a4 a33 a32 a31 a3 a22 a21 a2 a11 a1 a", "stroke", "#f00"},
					{"b55 b54 b53 b53 b51 b5 b44 b43 b42 b41 b4 b33 b32 b31 b3 b22 b21 b2 b11 b1 b", "stroke", "#ff0"},
					{"c55 c54 c53 c53 c51 c5 c44 c43 c42 c41 c4 c33 c32 c31 c3 c22 c21 c2 c11 c1 c", "stroke", "#0f0"},
					{"d55 d54 d53 d53 d51 d5 d44 d43 d42 d41 d4 d33 d32 d31 d3 d22 d21 d2 d11 d1 d", "stroke", "#0ff"},
					{"e55 e54 e53 e53 e51 e5 e44 e43 e42 e41 e4 e33 e32 e31 e3 e22 e21 e2 e11 e1 e", "stroke", "#00f"},
					{"f55 f54 f53 f53 f51 f5 f44 f43 f42 f41 f4 f33 f32 f31 f3 f22 f21 f2 f11 f1 f", "stroke", "#f0f"}},
				Text: []string{"The battlefield is divided into 6 regions... A through F.", "'A' in red, 'B' in yellow, 'C' in green, 'D' in cyan, 'E' in blue and 'F' in purple."}},

			{Title: "", Width: 70, PosX: 50, PosY: 85, Background: "#888888a0", Order: []string{"menu tutor"},
				Hilite: [][]string{{"a b c d e f", "stroke", "#fff"}},
				Black:  []string{}, White: []string{"Nd32"},
				Text: []string{"Surrounding the compass rose <*> at the center of the board: a,b,c,d,e,f make up the center ring...",
					"so a pawn just above <*> is notated: 'Pa'", "A Bishop, to the upper left of <*> is denoted as 'Bf'"}},

			{Title: "", Width: 70, PosX: 50, PosY: 30, Background: "#888888a0", Order: []string{"menu tutor"},
				Hilite: [][]string{{"d32", "stroke", "#00f"}},
				Black:  []string{}, White: []string{"Nd32"},
				Text:   []string{"The Knight highlighted in red wants to go to <d>, since he is already selected, move him to now..."},
				Answer: [][]string{{"", "That is not how a knight even moves.", "22,60,4,#F66,#000"}, {"d", "Thats the correct position.", "15,60,4,#6F6,#FF0"}, {"e c22 c33 d51 d55 e4 e31 e21", "The Knight can move there, but that is not where he want to be.", "25,70,4,#aa6,#000"}},
				Hint:   []string{"Its next to the compass rose.||22,60,4,#F66,#000"}},

			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#00000010",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},

			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#00000010",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Pawn": {
		Step: []Step{
			{Title: "Pawn", Width: 70, PosX: 50, PosY: 35, Background: "#20a0a070", Order: []string{"menu tutor"},
				Black: []string{"Pa31", "Pf33"}, White: []string{"Pc33", "Pd31"},
				Text: []string{"The lowly, humble pawn.  They are your front line; first to fight and to die for their King.  Alone, they are weak and vulnerable, but united, their formitability dictates the course of battle.",
					"The pawn is the most fundamental aspect of Chexx.  They will be the focus of you strategy since what tactics you employ by the other pieces will be derived from the positioning of your pawn structure."},
				Answer: [][]string{{"a", "Test.", "30,60,6,#f00,#20202070"},
					{"b", "This is a longer blurb. Hopefully this is contained nicely.", "3,60,4,#f00,#20202070"},
					{"c", "Multiple lines.||Can you hangle it?||It has to be at least four lines.||This is the forth line.", "20,60,6,#f00,#20202070"},
					{"d", "Multiple lines of small text.||Can it still hangle it?||It has to be at least four lines.||This is the forth line.", "20,60,2,#f00,#20202070"},
					{"e", "Those pawns don't belong to your army.", "10,52,5,#6F6,#80808040"},
					{"f", "Those pawns don't belong to your army.   ", "10,52,5,#6F6,#80808040"},
				},
			},

			{Title: "Pawn", Width: 70, PosX: 50, PosY: 30, Background: "#20a0a070",
				Hilite: [][]string{{"d", "stroke", "#0f0"}, {"d11 c11", "stroke", "#f00"}, {"d1", "stroke", "#00f"}},
				Black:  []string{}, White: []string{"Pd1"},
				Text: []string{"If Chess is familiar to you, this will be as you might expect.",
					"h2:::The pawn move forward one space at a time. Although their attacks are only to the forward flanks.",
					"Below, the center pawn selected at <d1>, shows in green where it can move to if the space is unoccupied.  In red are the spaces to where this pawn can attack an enemy piece.  Only when an enemy piece is present may this pawn take and accupy this space."}},
			{Title: "Pawn", Width: 70, PosX: 50, PosY: 40, Background: "#20a0a070",
				Hilite: [][]string{{"c22 d21", "stroke", "#00f"}},
				Black:  []string{}, White: []string{"Pc22", "Pd1", "Pd21"},
				Text: []string{"Joining the <d1> pawn, are <c22> and <d21> pawns to <d1> rear flanks.", "Since the pawns are c22 and d21 'attack' the d1 space, occupied by one of their own, that d1 pawn is said to be protected by the c22 and d21 pawns.  What this really means is that if the d1 pawn were taken, there would be potential consequesnce."}},

			{Title: "Pawn Formations", Width: 70, PosX: 50, PosY: 40, Background: "#20a0a070",
				Hilite: [][]string{{"c22 c32 c42 d3 d31", "stroke", "#00f"}},
				Black:  []string{}, White: []string{"Pc22", "Pc32", "Pc42", "Pd3", "Pd31"},
				Text: []string{"h2:::Pawns that protect each other in such a formation are said to be a 'pawn chain'.",
					"Such a configuration can be quite formitable.  Used wisely, these formation can cost many times what these individual pawns are worth."}},

			{Title: "", Width: 70, PosX: 50, PosY: 20, Background: "#20a0a070",
				Black: []string{"Pa1", "Pf11", "Pa11", "Pa22", "Pa33"}, White: []string{"Pc22", "Pc32", "Pc42", "Pd2", "Pd31"},
				Text: []string{"h2:::You will play White... select the lead pawn, and move him forward one space."},
				Answer: [][]string{{"", "Incorrect.", "25,60,6,#f00,#20202050"},
					{"a1 f11 a11 a22 a33", "Those pawns don't belong to your army.   ", "10,52,5,#6F6,#80808040"},
					{"c22 c32 c42 d2 d31", "", "", "~"}, {"c22~c", "Not that far.", "30,60,4,#6F6,#50505050"},
					{"c22~c11", "Ok, good start.", "25,60,4,#4dd,#a0a0a0a0", "-"}},
				Hint: []string{"A good leader leads by first doing.||25,90,3,#0f0,#000"},
			},

			{Title: "", Width: 70, PosX: 50, PosY: 20, Background: "#20a0a070",
				Black: []string{"Pa", "Pf11", "Pa11", "Pa22", "Pa33"}, White: []string{"Pc11", "Pc32", "Pc42", "Pd2", "Pd31"},
				Text: []string{"h3:::Nice.... the pawn advances forward 1 space,  but now, that lead pawn is all by himself.  Quite unfortunate for a pawn.",
					"Our strategy is to disrupt blacks ranks with a right flank attack.  So Pc32 will take the lead.  Now on a pawn's starting position, he can optionally charge forward two spaces.  From then on, he marches on with his signular focus, one space at a time.",
					"h2:::Overtake the lead pawn with his right support pawn!"},
				Answer: [][]string{{"", "Incorrect.", "25,60,6,#f00,#20202050"},
					{"a f11 a11 a22 a33", "Don't presume to command me!  You are the enemy!    ", "8,51,4,#f00,#00330060"},
					{"c11 c32 c42 d2 d31", "", "", "~"},
					{"c32~c21", "<c32> is meant for greatness!  Be bold an move that extra space.  ", "10,55,3,#af4,#00000030", "-"},
					{"c32~c1", "Brilliant!", "67,63,6,#6f6,#ff00ff44", "-"}},
				Hint: []string{"Look at pawns that might take the lead by moving 2 spaces forward.||5,100,3,#0f0,#000"},
			},

			{Title: "", Width: 70, PosX: 50, PosY: 30, Background: "#20a0a070",
				Black: []string{"Pa", "Pf11", "Pa11", "Pa22", "Pb2"}, White: []string{"Pc11", "Pc1", "Pc42", "Pd2", "Pd31"},
				Text: []string{"h2:::Your new lead pawn will need more back-up.  Support his right flank."},
				Answer: [][]string{{"", "Incorrect.", "30,60,6,#f80,#20202050"},
					{"a f11 a11 a22 b2", "Order me again and I shall have your head!   ", "16,51,4,#f00,#ffff0060"},
					{"c11 c1 c42 d2 d31", "", "", "~"},
					{"c42~c31", "HEY! <c42> , get into the fight! ", "25,81,4,#6f6,#ffff0060", "-"},
					{"c42~c2", "Welcome to glorious combat.   ", "30,52,5,#ff6,#80408050", "-"}},
				Hint: []string{"The lead pawn only has support from his left flank.||20,100,3,#0f0,#000",
					"There is a pawn all by himself doing nothing.  Give him a purpose.||10,100,3,#0f0,#000"}},

			{Title: "", Width: 70, PosX: 50, PosY: 28, Background: "#20a0a070",
				Black: []string{"Pf11", "Pa", "Pb", "Pb1", "Pb2"}, White: []string{"Pd11", "Pd", "Pc", "Pb11", "Pb22"},
				Text: []string{"h2:::Lets fast foward a few moves...  time for some bloodshead.",
					"It would have been nice if black would take first at <b11>, but your rival understands that after <b> takes <b11>... and the counter attack <b22> takes <b11>, his forces will have been divides in the center and ours still in tact.",
					"h4:::We will therefore take the initiative.  Take <b> with <b11>."},
				Answer: [][]string{{"", "Incorrect.", "60,70,6,#f80,#20202050"},
					{"f11 a b b1 b2", "I will shower thrice to rid myself of your stench.", "12,67,4,#f6f,#66660040"},
					{"d11 d c b11 b22", "", "", "~"},
					{"b11~b", "Blood has been drawn.   ", "30,70,5,#F00,#005555a0", "-"}},
				Hint: []string{"There is only one pawn that can attack.||30,100,3,#0f0,#000",
					"Attacking moves a pawn to a forward flank, not straight ahead.||10,100,3,#0f0,#000"}},

			{Title: "", Width: 70, PosX: 50, PosY: 30, Background: "#20a0a070",
				Black: []string{"Pf11", "Pb", "Pb1", "Pb2"}, White: []string{"Pd11", "Pd", "Pc", "Pb22"},
				Text: []string{"h2:::Black has taken our pawn.  We will sings songs about his bravery.",
					"Each side now has an isolated pawn.  You will have to have special consideration for such a weakness.  Spend at least as much time plotting your opponent's same vulnerabilities."}},

			{Title: "Pawn", Width: 70, PosX: 50, PosY: 40, Background: "#20a0a070",
				Black: []string{"Ka4"},
				White: []string{"Kd4", "Pd43", "Pd32", "Pd21", "Pd2", "Pc22", "Pc32", "Pc42"},
				Text: []string{"A pawn, especially, must think as a team.  Valliant a pawn might be, standing alone he is simply a casualty waiting happen.  He needs his fellow soldiers' support.",
					"A single pawn could mean the difference between victory and defeat."}},
		},
	},
	"Spearman": {
		Step: []Step{
			{Title: "Spearman", Width: 70, PosX: 50, PosY: 45, Background: "#20f02050", Order: []string{"menu tutor"},
				Black: []string{"Sa1"},
				White: []string{"Sd2"},
				Text: []string{"If the pawn is our front line, then the spearman is his brother in arms.  A spearman marches forward just as the pawn.  The difference is that he attacks the immediate spaces to the forward diagonals rather than the forward columns.  So in truth, what is a pawn in Chess is actually the spearman in Chexx.",
					"So the tactics of spearmen are of a parallel nature to those employed by pawns.  But the differences are important.  Exploiting their contributions to the fight, and knowing their weaknesses will be how to overcome your adversary."}},
			{Title: "", Width: 50, PosX: 50, PosY: 25, Background: "#20f02050",
				Hilite: [][]string{{"f2 a b2 c2 d e2", "stroke", "#0f0"}},
				Black:  []string{"Sf31", "Sa1", "Sa33"},
				White:  []string{"Sc31", "Sd1", "Sd33"},
				Text:   []string{"h4:::Spearmen march forward the same way pawns do.", "In green are the spaces to which these spearmen can march forward, lest they be occupied by forces of either army."}},
			{Title: "", Width: 70, PosX: 50, PosY: 25, Background: "#20f02050",
				Hilite: [][]string{{"e33 f1 f b b1 b31", "stroke", "#fa0"}, {"c1 b33 c e e1 e31", "stroke", "#f0a"}},
				Black:  []string{"Sf31", "Sa1", "Sa33"},
				White:  []string{"Sc31", "Sd1", "Sd33"},
				Text: []string{"h4:::Now, shown in orange, are the attacks of the black spearmen.  The purple are white's attacks.",
					"Notice how spearmen are vulnerable to close quarters combat."}},
			{Title: "", Width: 70, PosX: 50, PosY: 25, Background: "#20f02050",
				Hilite: [][]string{{"c e", "stroke", "#f0a"}, {"d1", "stroke", "#08f"}},
				Black:  []string{"Sf31", "Sa1", "Sa33", "Pc", "Pe"},
				White:  []string{"Sc31", "Sd1", "Sd33", "Pc11", "Pd11"},
				Text: []string{"h4:::The spearman's support role can be demonstrated with the addition of these locked pawns.",
					"See that the <d1> spearman's attack over the pawn's shoulder can break an otherwise locked position."}},
			{Title: "", Width: 40, PosX: 30, PosY: 50, Background: "#20f02050",
				Black: []string{"Sa21", "Sa22", "Sb2", "Sb3", "Sb4"},
				White: []string{"Sc22", "Sc21", "Sc2", "Sc3", "Sc4"},
				Text:  []string{"h4:::Here are spearment from both armies in a standard pawn formation.", "Seems like an affective formation, right?"}},
			{Title: "", Width: 40, PosX: 30, PosY: 40, Background: "#20f02050",
				Hilite: [][]string{{"d1 c11 c1 b22 b33 b44 b55", "stroke", "#f84"}},
				Black:  []string{"Sa21", "Sa22", "Sb2", "Sb3", "Sb4"},
				White:  []string{"Sc22", "Sc21", "Sc2", "Sc3", "Sc4"},
				Text:   []string{"h4:::Here are spearment from both armies in a standard pawn formation.", "Seems like an affective formation, right?", "Wrong!  Pawns protect to the forward flanks, not spearmen.  So what does a spearmen formations look like?  Well, since spearmen attack to the forward diagonals..."}},
			{Title: "", Width: 40, PosX: 30, PosY: 70, Background: "#20f02050",
				Black: []string{"Sb11", "Sa11", "Sa2", "Sb2", "Sa44"},
				White: []string{"Sc33", "Sc21", "Sb22", "Sc3", "Sc51"},
				Text:  []string{"h4:::Spearman formations look like this.", "Quite a wedge, right?  And quite a lot of open spaces."}},
		},
	},
	"Knight": {
		Step: []Step{
			{Title: "Knight", Width: 70, PosX: 50, PosY: 50, Background: "#302010c0", Order: []string{"menu tutor"},
				Black: []string{"Na4"},
				White: []string{"Nd2"},
				Text: []string{"h2:::Knights: elite battle warriors.  Charging in were angels fear to tread.",
					"Devistating and cunning, a single Knight can bring the downfall of a reign."},
			},
			{Title: "", Width: 70, PosX: 50, PosY: 30, Background: "#302010c0",
				Black: []string{"Na4"},
				White: []string{"Nd2", "Nc5", "Nd53"},
				Text:  []string{"Let us begin by understanding how the Knight moves.", "h4:::Select each of white's Knights on <d2>, <d53> and <c5>.", "Try to get familiar with their movement pattern."},
				Answer: [][]string{{"d2", "A knight can move to as many as 12 positions.   ", "12,42,4,#0ff,#ffff0030", "hl|#ff0|c54 c55 d51 d52 d43 d33 e1 e c c1 c31 c42"},
					{"c5", "On a corner, a Knight may have as few as 4 options.   ", "6,42,4,#0ff,#ffff0030", "hl|#ff0|c42 c31 b33 b43"},
					{"d53", "Here on the edge, the Knight can reach 6 spaces only.  ", "3,52,4,#0ff,#ffff0030", "hl|#ff0|e3 e4 d22 d21 d3 d4"}},
			},
			{Title: "", Width: 85, PosX: 50, PosY: 20, Background: "#302010c0",
				Hilite: [][]string{{"e11 f b b11 c2 c31 c43 c44 d41 d42 d33 e2", "stroke", "#ff0"}, {"a b22 c42 d43 e21", "stroke", "#f00"}},
				Black:  []string{"Na4"},
				White:  []string{"Nd1"},
				Text: []string{"h2:::Knights cannot be blocked.  The spaces they move to are not dependent on any intermediate spaces being free.",
					"Their strength comes from their range, penetration, and mutiple attacks.  Each is an army unto themself.",
					"h2:::The knight jumps to the third ring of spaces of a different color.  That gives the knight up to 12 options, at least, when well placed near the center.", "Near sides and corners, a knight my have as few as four.  So, give the Knight room to gallup to reach his full affectiveness"},
			},
			{Title: "", Width: 85, PosX: 50, PosY: 35, Background: "#302010c0",
				Black: []string{"Na4"},
				White: []string{"Nb", "N*", "Nd11"},
				Text:  []string{"Let us test you equestrian skills.", "h4:::Tallyhoe!  Of these three knights, only two protect each other.  Select the unprotected knight and move him to a position where the others can protect him."},
				Answer: [][]string{{"", "Sorry, but that is incorrect.", "30,75,6,#f80,#00000080"},
					{"b * d11", "", "", "~"},
					{"*~c21", "Excellant. The trifecta of might! ", "23,80,4,#0ff,#ffff0030", "-||hl|#ff0|b d11 c21"},
					{"b~c21 d11~c21", "Not bad. But there is a better option.", "22,72,4,#0ff,#ffff0030", "-"}},
			},
			{Title: "", Width: 85, PosX: 50, PosY: 25, Background: "#302010c0",
				Hilite: [][]string{{"b44 c4 c52 c53 c44 d3 d21 * b21 b32 b31 c2 d1 e11 f1 f22 a2 a32 a33 c33 d43 d42 e3 e31 e22 a c1 ", "stroke", "#0ff"}},
				Black:  []string{"Na4"},
				White:  []string{"Nb", "Nc21", "Nd11"},
				Text: []string{"h4:::Right you are.  Three key spaces on the board controlled by redundant defences.  It would take a fine strategy and a lot of sacrafice to unseat this stronghold.",
					"These three knights cover all of this area.  But there are distinct vulnerabilities.  ", "h2:::See how they might be attacked from right under thier noses?"},
			},
			{Title: "", Width: 85, PosX: 50, PosY: 25, Background: "#302010c0",
				Hilite: [][]string{{"", "stroke", "#0ff"}},
				Black:  []string{"Rc1"},
				White:  []string{"Nc"},
				Text: []string{"A knight is a master of close quarters combat.  Although he can't attack within that radius, he is just one move away from doing so.  Even better, there are two options for attacking any space within.",
					"h2:::That rook is right next to your knight.  What can he do to attack back?"},
				Answer: [][]string{{"", "That is incorrect.", "40,50,6,#f80,#20202050"},
					{"c", "", "", "~"},
					{"c1", "Remove thy mitts, villian!", "20,70,6,#f80,#20202050"},
					{"c~d21 c~c32", "Unfortunate move.||That rook will have your lunch.||Reset and try again.", "25,35,5,#f80,#20202050", "-"},
					{"c~a22 c~b32", "Unfortunate move.||That rook will have your lunch.||Reset and try again.", "25,75,5,#f80,#20202050", "-"},
					{"c~b33 c~f11 c~a1", "Sometimes retreat is the best move.||But the opportunity stands that||you might find safety in an||offensive position.", "20,70,4,#f80,#20202050", "-"},
					{"c~c31 c~e1 c~e11", "Sometimes retreat is the best move.||But the opportunity stands that||you might find safety in an||offensive position.", "30,30,4,#f80,#20202050", "-"},
					{"c~b2", "Great job.  Either <b2> or <d21> will turn||the tables on the rook. Bonus points to you ||if you found both moves.", "7,65,4,#f80,#20202050", "-"},
					{"c~d2", "Great job.  Either <b2> or <d21> will turn||the tables on the rook. Bonus points to you ||if you found both moves.", "7,35,4,#f80,#20202050", "-"},
					{"c1", "Remove thy mitts.", "60,40,6,#f80,#20202050", "~"}},
			},
			{Title: "", Width: 85, PosX: 50, PosY: 20, Background: "#302010c0",
				Black: []string{"Kf33", "Rf1", "Rc2", "Be3", "Bf32", "N*", "Qb3", "Sb2"},
				White: []string{"Kc33", "Rb1", "Nc1", "Bd22", "Bd33"},
				Text: []string{"Here is an example of how devistating a knight can be.  Examine this scenario... first look at how extensive blacks reach is and how quickly black could run roughshod over white's forces.",
					"h4:::Black is up a queen and rook.  The situation for white is grim. But a single Knight can shift the ballance of power.  What is white's best option?"},
				Answer: [][]string{{"", "That is incorrect.", "60,70,6,#f80,#f0a"},
					{"c1 b32", "", "", "~"},
					{"c33 d22 d33", "This is a Knight's tutorial...", "15,35,4,#0ff,#ff0"},
					{"f1 c2 e3 f32 * b3 b2", "I wretch at your proximity.", "10,55,4,#0ff,#ff0"},
					{"f33", "Filthy knave! Be gone from my sight.", "19,24,4,#000,#0ff"},
					{"b1~a22", "Indeed your Rook threatens the King, but in the quite impotent manner.||Yes, the attack is guarded by b32 Knight, but so Black's x Knight.  The exchange would||leave you trading Knight for both Rook and Knight.", "22,72,4,#0ff,#ff0"},
					{"c1~a11", "Hazzah!!  Rook, Queen and King are all in the Knight's sights.  Black||has no ther option than to sacrafice its Queen to save her King.", "16,95,3,#0ff,#ff0", "-||hl|#ff0|f33 b3 f1"},
					{"c1~a", "Attacking the King is a proven strategy, but in this case, its||despiration.  There is victory to be found: look out 2 moves ahead.", "14,97,3,#0ff,#ff0", "hl|#ff0|f33||hl|#f00|a"}},
				Hint: []string{"What knight can attack three major pieces?||30,100,3,#0f0,#000"},
			},
			{Title: "", Width: 85, PosX: 50, PosY: 15, Background: "#302010c0",
				Black: []string{"Ka2", "Rf1", "Rc2", "Be3", "Bf32", "N*", "Qb3", "Sb2"},
				White: []string{"Kc33", "Rb1", "Na11", "Bd22", "Bd33"},
				Text:  []string{"Resolved that his Queen is lost, the King moves to safety, now the Queen in yours!", "h4:::But, there is a better option... Reflect a moment to see how the noble Knight may yet inflict even greater harm."},
				Answer: [][]string{{"", "That is incorrect.", "60,70,6,#f80,#f0a"},
					{"a11 b32", "", "", "~"},
					{"c33 d22 d33", "This is still the Knight's tutorial...", "10,55,4,#0ff,#ff0"},
					{"f1 c2 e3 f32 * b3 b2", "I wretch at your proximity.", "10,55,4,#0ff,#ff0"},
					{"a2", "Vile wretch! You will beg me for a quick death.", "12,25,4,#0ff,#ff0"},
					{"a11~b3", "As I said, you can take the Queen.  That makes up quite a bit of ground,||but you are still a Rook down and Black is bearing down on you.|| look for the better option.", "12,79,3,#0ff,#ff0", "hl|#ff0|b3"},
					{"a11~f1", "Great insight!  Down a rook, and the King must again flee.", "16,95,3,#0ff,#ff0", "-"}},
				Hint: []string{"Attack the King again...||30,100,3,#0f0,#000", "Take a piece, but the Queen can wait... trust me.||30,100,3,#0f0,#000"},
			},
			{Title: "", Width: 85, PosX: 50, PosY: 15, Background: "#302010c0",
				Hilite: [][]string{{"d33 d22 b1", "stroke", "#0f0"}, {"a2 a21 a31 a1 f22 f33", "stroke", "#ff0"}},
				Black:  []string{"Ka2", "Rc2", "Be3", "Bf32", "N*", "Qb3", "Sb2"},
				White:  []string{"Kc33", "Rb1", "Nf1", "Bd22", "Bd33"},
				Text:   []string{"The King is under attack by the Knight....  bishops <d33> and <d22> block the King's advance to <a2>, <a21> or <a31>.  The rook at <b1> cuts off <a1> and <f22>.  The only place for the King to go is <a3>."},
			},
			{Title: "", Width: 85, PosX: 50, PosY: 15, Background: "#302010c0",
				Black: []string{"Ka3", "Rc2", "Be3", "Bf32", "N*", "Qb3", "Sb2"},
				White: []string{"Kc33", "Rb1", "Nf1", "Bd22", "Bd33", "Nb32"},
				Text:  []string{"Make his failure complete."},
				Answer: [][]string{{"", "That is incorrect.", "60,70,6,#f80,#f0a"},
					{"a11 b32", "", "", "~"},
					{"c33 d22 d33", "This is still the Knight's tutorial...", "10,55,4,#0ff,#ff0"},
					{"c2 e3 f32 * b3 b2", "With all due respect... eat a stool.", "10,55,4,#0ff,#ff0"},
					{"a3", "You varlet! Get away.", "12,25,4,#0ff,#ff0"},
					{"b32~a22", "Not entirely devoid of merrit, but you let the King escape||while an alternate move allows you to capture the Queen.", "12,79,3,#0ff,#ff0", "hl|#ff0|b3"},
					{"f1~a11", "...Thrice, the King must flee... and now,||the Queen is yours for the taking.", "26,95,3,#0ff,#ff0", "-"}},
				Hint: []string{"Attack the King again...||30,100,3,#0f0,#000", "Attack the Queen with that same move.||30,100,3,#0f0,#000"},
			},
			{Title: "", Width: 85, PosX: 50, PosY: 15, Background: "#302010c0",
				Black: []string{"Kf44", "Rc2", "Be3", "Bf32", "N*", "Qb3", "Sb2"},
				White: []string{"Kc33", "Rb1", "Na11", "Bd22", "Bd33"},
				Text:  []string{"Without a Queen and a second rook, it is you who has the upper hand.  Once bearing down on your King, the enemy has lost his advantage and now this match is yours to lose.", "h4:::In Chess, such scenarios do happen.  It takes careful stategizing, but even the threat of being led to such a position can be useful."},
			},
			{Title: "", Width: 85, PosX: 50, PosY: 15, Background: "#302010c0",
				Black: []string{"Na4"},
				White: []string{"Nd3"},
				Text:  []string{"Knights are powerful given the right opportunity.  As the commander of your forces, it is your job to set up your enemy for the thrashing a knight is designed to deliver.  In your scheming, it pays to consider tactics that use Knights to spring a trap."},
			},
		},
	},
	"Bishop": {
		Step: []Step{
			{Title: "Bishop", Width: 70, PosX: 50, PosY: 30, Background: "#500060a0", Order: []string{"menu tutor"},
				Black: []string{"Ka4"},
				White: []string{"Bd2", "Bc42", "Bd42"},
				Text:  []string{"h2:::His grace, the bishop.  Seedily sliding through enemy lines to eviserate his enemy from within.", "h4:::Plan carefully your formations: watch out for thouse diagonals that pierce through!  They are a bit harder to percieve on the hexagonal grid."},
			},
			{Title: "", Width: 70, PosX: 50, PosY: 40, Background: "#500060a0",
				Black: []string{"Ka4"},
				White: []string{"Bd2", "Bc42", "Bd42"},
				Text:  []string{"I can't help coming back to Chess.  Well, here we go again.", "h4:::In Chess, you have two Bishops: one on a light square, and one on a dark square.  And on their repective colors they will remain.", "h4:::As it is with Chexx, you will command bishops on a light space, and one on a dark space.  And for the entire game, they will never venture off on their respective colors.  Now in Chexx, there is a third color, and therefore a third bishop.  That last bishop lives in the realm of grey."},
			},
			{Title: "", Width: 70, PosX: 50, PosY: 40, Background: "#500060a0",
				Black: []string{"Ka4"},
				White: []string{"Bd2", "Bc42", "Bd42"},
				Text:  []string{"The Chess, a bishop will reside on no more than half the board. Quite a disadvantage.", "h4:::For Chexx, that disadvantage is even worse.  For each Bishop will only ever reach a third on the board.  They can't protect one another, but they can work as a team."},
			},
			{Title: "", Width: 70, PosX: 50, PosY: 40, Background: "#500060a0",
				Black: []string{"Ka4"},
				White: []string{"Bd2", "Bc42", "Bd42"},
				Text:  []string{"h4:::Lets begin with selecting the dark space bishop."},
				Answer: [][]string{{"d42", "See how his only moves||are to dark spaces.", "45,59,4,#f80,#f0a", "hl|#0f0|d3 c43 c52 d51 d54 d33 e31 e43 e55 d21 d b a32 a43"},
					{"d42", "See how his only moves are to dark spaces.", "70,70,6,#f80,#f0a", "hl|#0f0|d3 c43 c52 d51 d54 d33 e31 e43 e55 e21 d b a22 a43"},
					{"d2 c42", "This bishop isn't on a dark space.", "25,99,5,#f80,#f0a"}},
			},
			{Title: "", Width: 70, PosX: 50, PosY: 40, Background: "#500060a0",
				Black: []string{"Ka4"},
				White: []string{"Bd2", "Bc42", "Bd42"},
				Text:  []string{"This holds true for the other bishops too.  The bishop on a white space will only occupy white spaces.  The bishop on grey will only occupy grey spaces."},
			},
			{Title: "", Width: 35, PosX: 20, PosY: 15, Background: "#500060a0",
				Black: []string{"Kf33", "Rb", "Rb2", "Qb33", "N*", "Nf11"},
				White: []string{"Be3", "Bd33", "Bc11", "Nf", "Ne22", "Kd31", "Pec41"},
				Text:  []string{"When is a bishop powerful?  Against powerful pieces caught within a bishop's domain.  Here, a King and rook both occupy black spaces.  What single move can guarantee the caputure of a major piece?"},
				Answer: [][]string{{"", "Bad move.", "40,99,5,#f80,#f0a"},
					{"d33 e3", "", "", "~"},
					{"f33", "The flies you attract are not nearly||as annoying as the sight of your face.", "30,20,3,#000,#f99"},
					{"b b3 a32 * f11", "I shall introduce your face to my palm.", "30,20,3,#ff6,#000"},
					{"d33~c31", "Nice. The rook is pinned, unable to move lest the King be||captured.  He must first move his king before moving the rook.||Notice the queen on grey.  How can this be exploited?", "15,75,3,#f80,#f0a", "-||hl|#0f0|"},
					{"c11~d11", "Quite right.  The center knight is pinned to protect his Queen.||The mighty knight reduced to a mere blocker.", "35,99,5,#f80,#f0a"}},
			},
		},
	},
	"Rook": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Archer": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Queen": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"King": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Prince": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Princess": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Special": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Promotion": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Forks": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Skewers": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Pins": {
		Step: []Step{
			{Title: "", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Tactics": {
		Step: []Step{
			{Title: "Tactics", Width: 70, PosX: 50, PosY: 50, Background: "#f0202050",
				Black: []string{},
				White: []string{},
				Text:  []string{""}},
		},
	},
	"Unimplemented": {
		Step: []Step{
			{Title: "Unimplemented", Width: 70, PosX: 50, PosY: 50, Background: "#f020f040",
				Black: []string{},
				White: []string{},
				Text:  []string{"Sorry, perhaps check back later for an update."}},
		},
	},
}

type Thing struct {
	Lesson string `json:"lesson"`
}

func Tutorial(w http.ResponseWriter, r *http.Request) {

	// respDump, err := httputil.DumpRequest(r, true)
	// if err != nil {
	// 	log.Fatal(err)
	// }

	// fmt.Printf("RESPONSE:\n%s", string(respDump))
	var s Thing

	err := json.NewDecoder(r.Body).Decode(&s)

	if err != nil {
		log.Fatalf("Error happened in JSON Decode. Err: %s", err)
		return
	}

	res, err := json.Marshal(Lessons[s.Lesson])
	if err != nil {
		log.Fatalf("Error happened in JSON marshal. Err: %s", err)
		return
	}
	// fmt.Println(string(res))
	utils.CorsHeader(w)
	w.WriteHeader(http.StatusOK)
	w.Write(res)
}
